project_id = "yfgjbvbfqluracojxweh"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
shadow_port = 54320
major_version = 15

[studio]
enabled = true

[inbucket]
enabled = false

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true

[functions]
verify_jwt = { enabled = false }
